POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa28gTmlzc2luZW4iLCJpZCI6IjY4ZGI3ZGRiYjFlZjdiMDM5MDYyMWM2NyIsImlhdCI6MTc1OTIxNTkxNX0.hVGG00vYlVZ8PjPfld1f-vh7-niob7uDZtgUvvp6w90

{
  "title": "Test title",
  "author": "Niko Nissinen",
  "url": "https://example.com",
  "likes": 10
}