POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa28gTmlzc2luZW4iLCJpZCI6IjY4ZGI3ZGRiYjFlZjdiMDM5MDYyMWM2NyIsImlhdCI6MTc1OTIxNzE0Mn0.xdPQu5Exlcec7J51OVE3n8IJH7MsFxMvogEY_dVw2Lk

{
  "title": "Test title",
  "author": "Niko Nissinen",
  "url": "https://example.com",
  "likes": 10
}